In [15]:
import numpy as np

In [ ]:
# การ broadcasting ที่อยู่ใน Library Numpy นั้นมีไว้เพื่อสำหรับใช้ในการคูญ Matrix หรือ Array ที่ Shape(ขนาดไม่เท่ากัน) ไม่เท่ากัน

In [16]:
A = np.array([[56.0,0.0,4.4,68.0],[1.2,104.0,52.0,8.0],[1.8,135.0,99.0,0.9]])

print (A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [17]:
cal  = A.sum(axis=0)
print (cal)

[ 59.  239.  155.4  76.9]


In [18]:
percentage = 100*A/cal.reshape(1,4) # ต้อง reshape ตลอด เพืื่อ Bug prevention
print (percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [20]:
a = np.random.randn(1,3)
b = np.random.randn(3,3)

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject