In [1]:
import numpy as np

In [2]:
a = np.random.rand(5)
print (a)

[0.63470876 0.78362279 0.39765002 0.78236846 0.31627414]


In [3]:
print (a.shape)

(5,)


In [4]:
print (a.T)

[0.63470876 0.78362279 0.39765002 0.78236846 0.31627414]


In [5]:
print (np.dot(a,a.T))

1.8871751557595555


In [ ]:
a = np.random.rand(5,1)
print (a)

[[0.81057246]
 [0.47684686]
 [0.95708053]
 [0.1279926 ]
 [0.67336216]]


In [18]:
print (a.T)

[[0.81057246 0.47684686 0.95708053 0.1279926  0.67336216]]


In [21]:
print (np.dot(a,a.T))

[[0.65702771 0.38651894 0.77578312 0.10374728 0.54580882]
 [0.38651894 0.22738293 0.45638085 0.06103287 0.32109063]
 [0.77578312 0.45638085 0.91600313 0.12249923 0.64446181]
 [0.10374728 0.06103287 0.12249923 0.01638211 0.08618538]
 [0.54580882 0.32109063 0.64446181 0.08618538 0.4534166 ]]


In [22]:
a = np.random.rand(5,1)
print (a.T)

[[0.63665797 0.21742651 0.43359116 0.58456829 0.24698551]]


In [ ]:
# (5,1) จะเป็น Colume Vector
# (1,5) จะเป็น row Vector
a.shape

(5, 1)

In [28]:
d = np.random.randn(2,3)
f = np.random.randn(2,1)
c = d+f

print (c)

[[ 2.68835561  2.24232264 -0.96401226]
 [-0.62214128 -0.49424104  0.24718486]]


In [32]:
a=np.array([[2,1],[1,3]])

print (a*a)

[[4 1]
 [1 9]]
