In [9]:
import numpy as np

In [10]:
A = np.array([[56.0,0.0,4.4,68.0],[1.2,104.0,52.0,8.0],[1.8,135.0,99.0,0.9]])

cal = A.sum(axis=0)

In [16]:
percentage = 100*A/cal.reshape(1,4)
print (percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [18]:
#vectorized version

import numpy as np
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

In [19]:
# for loop
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time. time()

print (c)
print ("for loop:"+ str(1000*(tic-toc))+"ms")

# vectorized version
tic = time.time()
c = np.dot(a,b)
toc = time.time()

print (c)
print ("vectorized versoin:"+ str(1000*(tic-toc))+"ms")


249834.5712000408
for loop:-285.37797927856445ms
249834.57120003982
vectorized versoin:-4.070043563842773ms
